package main;

public enum GameType {
    HUMAN__VS__HUMAN,
    HUMAN__VS__AI_MINMAX,
    AI_MINMAX__VS__AI_MINMAX,
    AI_MCTS__VS__AI_MINMAX,
    HUMAN__VS__AI_MCTS,
    HUMAN__VS__AI_RULE,
    AI_MINMAX__VS__AI_RULE,
    AI_MINMAX__VS__AI_RANDOM,
    AI_HYBRID__VS__HUMAN,
    AI_HYBRID__VS__AI_MINMAX,
    AI_HYBRID__VS__AI_RULE
}

